-- MySQL Script generated by MySQL Workbench
-- Sat Nov 13 19:26:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekt_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projekt_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekt_bd` DEFAULT CHARACTER SET utf8 ;
USE `projekt_bd` ;

-- -----------------------------------------------------
-- Table `projekt_bd`.`agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`agency` (
  `agency_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `website_address` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`agency_id`),
  UNIQUE INDEX `agency_id_UNIQUE` (`agency_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`drivers` (
  `driver_id` INT NOT NULL,
  `has_actual_medical_ecamination` TINYINT(1) NOT NULL,
  `has_actua_driving_license` TINYINT(1) NOT NULL,
  `agency_id` INT NOT NULL,
  PRIMARY KEY (`driver_id`),
  UNIQUE INDEX `driver_id_UNIQUE` (`driver_id` ASC) VISIBLE,
  INDEX `fk_drivers_agency1_idx` (`agency_id` ASC) VISIBLE,
  CONSTRAINT `fk_drivers_agency1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `projekt_bd`.`agency` (`agency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`localisation_squares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`localisation_squares` (
  `square_id` INT NOT NULL,
  `max_x` DOUBLE NOT NULL,
  `max_y` DOUBLE NOT NULL,
  `min_x` DOUBLE NOT NULL,
  `min_y` DOUBLE NOT NULL,
  `tram_accidents` INT NULL,
  `bus_accidents` INT NULL,
  PRIMARY KEY (`square_id`),
  UNIQUE INDEX `square_id_UNIQUE` (`square_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`causes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`causes` (
  `cause_id` INT NOT NULL,
  `cause_description` VARCHAR(300) NOT NULL,
  `amount_of_accidents` INT NULL,
  PRIMARY KEY (`cause_id`),
  UNIQUE INDEX `cause_id_UNIQUE` (`cause_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`actual_postion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`actual_postion` (
  `side_number` INT NOT NULL,
  `actual_longitude` DOUBLE NOT NULL,
  `actual_latitude` DOUBLE NOT NULL,
  UNIQUE INDEX `side_number_UNIQUE` (`side_number` ASC) VISIBLE,
  PRIMARY KEY (`side_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`vehicles` (
  `side_number` INT NOT NULL,
  `vehicle_type_id` INT NOT NULL,
  `agency_id` INT NOT NULL,
  `registrstion_number` VARCHAR(10) NOT NULL,
  `is_driving` TINYINT(1) NULL,
  `is_roadworthy` TINYINT(1) NULL,
  UNIQUE INDEX `registrstion_number_UNIQUE` (`registrstion_number` ASC) VISIBLE,
  PRIMARY KEY (`side_number`),
  UNIQUE INDEX `side_number_UNIQUE` (`side_number` ASC) VISIBLE,
  INDEX `fk_vehicles_agency1_idx` (`agency_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicles_actual_postion1`
    FOREIGN KEY (`side_number`)
    REFERENCES `projekt_bd`.`actual_postion` (`side_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicles_agency1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `projekt_bd`.`agency` (`agency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`vehicle_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`vehicle_type` (
  `vehicle_type_id` INT NOT NULL,
  `vehicle_type_name` VARCHAR(45) NOT NULL,
  `vehicle_type_description` VARCHAR(100) NULL,
  PRIMARY KEY (`vehicle_type_id`),
  UNIQUE INDEX `vehicle_type_id_UNIQUE` (`vehicle_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_type_vehicles1`
    FOREIGN KEY (`vehicle_type_id`)
    REFERENCES `projekt_bd`.`vehicles` (`vehicle_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`passes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`passes` (
  `user_mail` VARCHAR(255) NOT NULL,
  `level_of_authorization` TINYINT(15) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`user_mail`),
  UNIQUE INDEX `user_mail_UNIQUE` (`user_mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`users` (
  `mail` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `good_reports` INT NULL,
  `active_account` TINYINT(1) NOT NULL,
  PRIMARY KEY (`mail`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  CONSTRAINT `fk_users_passes1`
    FOREIGN KEY (`mail`)
    REFERENCES `projekt_bd`.`passes` (`user_mail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`accident_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`accident_details` (
  `accident_id` INT NOT NULL,
  `accident_detailscol` VARCHAR(45) NULL,
  `amount_of_other_vehicles_accessory` INT NULL,
  `hurt_passengers` INT NULL,
  `dead_passengers` INT NULL,
  `hurt_mpk_employees` INT NULL,
  `dead_passengers_employees` INT NULL,
  `affected_lines_ids` VARCHAR(45) NULL,
  `edited_by_mail` VARCHAR(255) NULL,
  `added_by_mail` VARCHAR(45) NULL,
  `accepted_by_mail` VARCHAR(45) NULL,
  UNIQUE INDEX `accident_id_UNIQUE` (`accident_id` ASC) VISIBLE,
  PRIMARY KEY (`accident_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`route_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`route_types` (
  `route_type_id` INT NOT NULL,
  `route_type_name` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `route_type_name_UNIQUE` (`route_type_name` ASC) VISIBLE,
  PRIMARY KEY (`route_type_id`),
  UNIQUE INDEX `route_type_id_UNIQUE` (`route_type_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`lines` (
  `line_id` INT NOT NULL,
  `line` VARCHAR(45) NOT NULL,
  `destination_1` VARCHAR(100) NOT NULL,
  `destination_2` VARCHAR(100) NOT NULL,
  `route_type_id` INT NOT NULL,
  PRIMARY KEY (`line_id`),
  UNIQUE INDEX `line_id_UNIQUE` (`line_id` ASC) VISIBLE,
  UNIQUE INDEX `lines_UNIQUE` (`line` ASC) VISIBLE,
  INDEX `fk_lines_route_types1_idx` (`route_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_lines_route_types1`
    FOREIGN KEY (`route_type_id`)
    REFERENCES `projekt_bd`.`route_types` (`route_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_bd`.`accident_main`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt_bd`.`accident_main` (
  `accident_id` INT NOT NULL,
  `side_number` INT NOT NULL,
  `location_longitude` DOUBLE NOT NULL,
  `location_latitude` DOUBLE NOT NULL,
  `line_id` INT NULL,
  `square_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  `cause_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`accident_id`),
  INDEX `fk_accident_main_localisation_squares1_idx` (`square_id` ASC) VISIBLE,
  INDEX `fk_accident_main_causes1_idx` (`cause_id` ASC) VISIBLE,
  INDEX `fk_accident_main_actual_postion1_idx` (`side_number` ASC) VISIBLE,
  INDEX `fk_accident_main_lines1_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_accident_main_accident_details1`
    FOREIGN KEY (`accident_id`)
    REFERENCES `projekt_bd`.`accident_details` (`accident_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_main_localisation_squares1`
    FOREIGN KEY (`square_id`)
    REFERENCES `projekt_bd`.`localisation_squares` (`square_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_main_causes1`
    FOREIGN KEY (`cause_id`)
    REFERENCES `projekt_bd`.`causes` (`cause_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_main_actual_postion1`
    FOREIGN KEY (`side_number`)
    REFERENCES `projekt_bd`.`actual_postion` (`side_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_main_vehicles1`
    FOREIGN KEY (`side_number`)
    REFERENCES `projekt_bd`.`vehicles` (`side_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accident_main_lines1`
    FOREIGN KEY (`line_id`)
    REFERENCES `projekt_bd`.`lines` (`line_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
